### ISSUE TITLE
Add dataset: lancaster_newsbooks

### ISSUE THREAD

**Issue by clancyoftheoverflow** [bigscience-workshop/lam#57] opened 2022-07-14 15:57 UTC
### A URL for this dataset

https://ota.bodleian.ox.ac.uk/repository/xmlui/handle/20.500.12024/2531

### Dataset description

The Lancaster Newsbooks Corpus contains two collections of English newsbooks from 1654 to 1655.

Size: 3,001,604 words.

### Dataset modality

Text

### Dataset licence

Other license

### Other licence

Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)

### How can you access this data

As a download from a repository/website

### Confirm the dataset has an open licence

- [X] To the best of my knowledge, this dataset is accessible via an open licence

**Comment by davanstrien** [comment] 2022-07-14 16:23
looks great!

**Comment by shamikbose** [comment] 2022-07-19 01:44
#self-assign

**Comment by shamikbose** [comment] 2022-07-19 17:21
@clancyoftheoverflow @davanstrien This dataset doesn't seem to have any labels. Can you clarify what the features of this dataset should be?

**Comment by shamikbose** [comment] 2022-07-19 19:57
#ready-for-review

**Comment by shamikbose** [comment] 2022-07-19 19:58
@clancyoftheoverflow @davanstrien In the absence of labels in this dataset, it only loads the `title`, `text` and `id` fields. It's live here: https://huggingface.co/datasets/shamikbose89/lancaster_newsbooks Please let me know if it needs any additional information

**Comment by davanstrien** [comment] 2022-08-15 12:44
Thanks for working on this, and apologies for taking so long to look at it. At the moment, I get an error when I try and load this dataset:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 8531: invalid start byte`

I didn't look into the cause yet but let me know if you want me to take a look at this too.

**Comment by shamikbose** [comment] 2022-08-17 15:51
@davanstrien I'm able to load this dataset without any issues. Maybe it's a Python encoding issue. I'm using Windows as my dev environment, so that might have something to do with it.

**Comment by davanstrien** [comment] 2022-08-18 12:30
I've opened a PR https://huggingface.co/datasets/shamikbose89/lancaster_newsbooks/discussions/1, which hopefully fixed the issue for me (running in Colab) -- could you check if it still works okay on Windows?

**Comment by davanstrien** [comment] 2022-09-12 10:37
I think this one can probably be transferred to the BigLAM repository now?

**Comment by shamikbose** [comment] 2022-09-12 15:09
Yeah, I just moved it

**Comment by davanstrien** [comment] 2022-09-12 15:22
Thanks for working on this one!

**Closed by davanstrien** 2022-09-12 15:22 UTC
Labels: dataset
